FROM kaixhin/cuda-torch

RUN luarocks install tds
RUN luarocks install torchx

RUN apt-get -y update && apt-get install -y python-dev wget python-numpy

ENV HDF5_MAJOR_REL       hdf5-1.8.16
ENV HDF5_MINOR_REL       hdf5-1.8.16
ENV HDF5_SRC_URL   http://www.hdfgroup.org/ftp/HDF5/releases

RUN cd /tmp                                                                        ; \
    echo "Getting: ${HDF5_SRC_URL}/${HDF5_MAJOR_REL}/${HDF5_MINOR_REL}/src/${HDF5_MINOR_REL}.tar"                ; \
    wget ${HDF5_SRC_URL}/${HDF5_MAJOR_REL}/${HDF5_MINOR_REL}/src/${HDF5_MINOR_REL}.tar                           ; \
    tar -xvf ${HDF5_MINOR_REL}.tar --directory /usr/local/src                      ; \
    rm ${HDF5_MINOR_REL}.tar                                                       ; \
    cd /usr/local/src/${HDF5_MINOR_REL}                                            ; \
    ./configure --prefix=/usr/local/hdf5                                           ; \
    make                                                                           ; \
    make check                                                                     ; \
    make install                                                                   ; \
    make check-install                                                             ; \
    for f in /usr/local/hdf5/bin/* ; do ln -s $f /usr/local/bin ; done             ; \
    cd /usr/local/src                                                              ; \
    export HDF5_DIR=/usr/local/hdf5                                               

RUN apt-get install -y libhdf5-serial-dev hdf5-tools
RUN git clone https://github.com/deepmind/torch-hdf5 /home/tlin/notebooks/torch-hdf5
RUN cd /home/tlin/notebooks/torch-hdf5 \
    && luarocks make hdf5-0-0.rockspec LIBHDF5_LIBDIR="/usr/lib/x86_64-linux-gnu/"
